[package]
name = "rust-monke"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contracts = "0.6.2"
enum-iterator = "0.7.0"
enum-display-derive = "0.1.1"